name: Tarea Automatizada de Limpieza de Inventarios

on:
  schedule:
    # Se ejecuta todos los días a las 04:00 AM UTC (Aproximadamente 01:00 AM en Argentina)
    - cron: '0 4 * * *'
  workflow_dispatch:
    # Esto te permite activar la limpieza manualmente desde la web cuando quieras probarla

jobs:
  limpieza:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno de Python
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.10'

    - name: Instalar librerías necesarias
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin google-api-python-client google-auth-oauthlib google-auth-httplib2

    - name: Ejecutar Script de Supervisión de Inactivos
      env:
        # Inyectamos de forma segura las credenciales ocultas en las variables de entorno del contenedor
        FIREBASE_SECRETS_JSON: ${{ secrets.FIREBASE_SECRETS_JSON }}
        GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
      run: python limpiador_inactivos.py
